#!/usr/bin/env python3
import sys
import subprocess
import datetime
import os

from buildboy.util import update_repo, expand_path, start_vm
# These are the virtual machines we're going to be building on.
from buildboy.vms import vms

def do_build(vm_data):
    """"""
    with start_vm(vm_data) as ssh:
        # Check for updates to the local build-boy script.
        print("Fetching updates...")
        ssh.run('cd build-boy && git fetch origin && git checkout main && git reset --hard origin/main')

        # Call the local build-boy build script.
        print("Running build...")
        ssh.run('cd build-boy/Scripts/' + vm_data['target'] + " && ./build")

        # All done, make the VM go to bed.
        print("Shutting down VM...")
        ssh.run("sudo shutdown now", warn = True)
                

def main():
    print("--------------------------------------")
    print("-      BUILD-BOY MASTER SCRIPT       -")
    print("--------------------------------------")
    print("")
    print("Good-evening.")
    print("The time is: " + str(datetime.datetime.now()))
    for vm in vms.values():
        try:
            print("--------------------------------------")
            print("-              BUILD-BOY             -")
            print("--------------------------------------")
            print("Starting build for {}".format(vm['target']))
            print()
            do_build(vm)
        
        except Exception as e:
            print("Failed to build for VM: {}".format(vm['target']))
            print(e)

    # Finally, tag the silico version and push back.
    update_repo(expand_path('~/silico'), "build")
    os.chdir(expand_path('~/silico'))
    sys.path.append(expand_path('~/silico'))
    import silico

    try:
        subprocess.run(["git", "tag", "v{}".format(silico.__version__) ], universal_newlines = True, check = True)
        subprocess.run(["git", "push", "--tags"])
    
    except Exception:
        # Already done this version.
        pass
    


# If we've been invoked as a program, call main().    
if __name__ == '__main__':
    sys.exit(main())
