#!/usr/bin/env python3

import sys
from pathlib import Path
sys.path.insert(0,str(Path("../").resolve()))
from buildboy import build

# If we've been invoked as a program, call main().
if __name__ == '__main__':
    sys.exit(build('Debian-Bullseye'), blender = "4.4", download_blender = True)
